=== nka11/CronosEnbourg/src/main/resources/CronosScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="cronosenbourg">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="listen"/>
        <xs:element ref="instance"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="listen">
    <xs:complexType>
      <xs:attribute name="iface" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="port" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="instance">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mbean" maxOccurs="unbounded"/>
        <xs:element ref="output" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="host" use="required" type="xs:string"/>
      <xs:attribute name="interval" use="required" type="xs:integer"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="output" use="required" type="xs:string"/>
      <xs:attribute name="port" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="mbean">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="operation"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="property" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="arg">
    <xs:complexType>
      <xs:attribute name="pos" use="required" type="xs:int"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="operation">
    <xs:complexType>
    	<xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="arg"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="property" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="output">
    <xs:complexType>
      <xs:sequence>
                <xs:element minOccurs="0" ref="oper" maxOccurs="unbounded"/>
                <xs:element maxOccurs="unbounded" ref="item"/>
      </xs:sequence>
      <xs:attribute name="className" use="required" type="xs:string"/>
      <xs:attribute name="file" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="item">
    <xs:complexType>
      <xs:attribute name="ind" use="required" type="xs:integer"/>
      <xs:attribute name="propertyref" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="oper">
    <xs:complexType>
    	<xs:attribute name="arg1propertyref" use="required"
    		type="xs:string" />
    	<xs:attribute name="arg2propertyref" use="required"
    		type="xs:string" />
    	<xs:attribute name="ind" use="required" type="xs:integer" />
    	<xs:attribute name="property" type="xs:string"></xs:attribute>
    	<xs:attribute name="operator" type="xs:string"></xs:attribute>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== nka11/CronosEnbourg/src/main/resources/CronosEnbourg.xml
<?xml version="1.0" encoding="UTF-8"?>
<cronosenbourg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CronosScheme.xsd">
	<listen iface="127.0.0.1" port="8888" />
	<instance name="default" output="toto.log" interval="10" host="udev3"
		port="44109">
		<mbean name="jboss.system:type=ServerInfo">
			<!--  attribute property is primary key across all mbeans objects -->
			<attribute name="FreeMemory" property="FreeMemory"/>
			<attribute name="TotalMemory" property="totalMemory"/>
		</mbean>
		<output file="toto-1.log" className="org.cronosenbourg.monitor.DefaultCSVOutput">
			<item ind="1" propertyref="FreeMemory"/>
			<item ind="0" propertyref="totalMemory"/>
		</output>
		<output file="target/toto-1.log" className="org.cronosenbourg.monitor.DefaultPropertiesOutput">
			<oper ind="2" property="usedMemory" operator="-" arg1propertyref="totalMemory" arg2propertyref="FreeMemory"/>
			<item ind="0" propertyref="totalMemory"/>
		</output>
	</instance>
</cronosenbourg>
